spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab_operations
    username: lab_user
    password: lab_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  flyway:
    enabled: false

logging:
  level:
    com.sivalab.laboperations: DEBUG
