spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lab_operations_test
    username: postgres
    password: Ramz#4419
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  test:
    jvm:
      args: --enable-native-access=ALL-UNNAMED

  flyway:
    enabled: false

logging:
  level:
    com.sivalab.laboperations: DEBUG
